/* Responsive page ordering: one global save bar, mobile arrows + desktop drag/drop. */
(function(){
 const ENDPOINT='https://jzswtwicvgppisasrkqe.supabase.co/functions/v1/creator-projects';let currentSlug='',runToken=0;
 function password(){let p=sessionStorage.getItem('creatorPassword');if(!p){p=prompt('أدخلي كلمة مرور لوحة غادة')||'';if(p)sessionStorage.setItem('creatorPassword',p)}return p}
 async function request(payload){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,password:password()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر حفظ ترتيب الصفحات');return d}
 function cleanup(){document.querySelectorAll('#pageOrderBar,.page-order-bar,.page-order-controls,.page-drag-handle').forEach(x=>x.remove())}
 function findContainer(count){const panel=document.querySelector('.panel');if(!panel)return null;const candidates=[...panel.querySelectorAll('div')].filter(d=>{const kids=[...d.children];return kids.length===count&&kids.every(c=>c.tagName==='DIV'&&c.querySelector('strong')&&c.querySelector('p'))});return candidates.sort((a,b)=>a.querySelectorAll('div').length-b.querySelectorAll('div').length)[0]||null}
 function renumber(c){[...c.children].forEach((card,i)=>{const s=card.querySelector('strong');if(s)s.textContent=s.textContent.replace(/^\d+\./,(i+1)+'.')})}
 function dirty(){const bar=document.getElementById('pageOrderBar');if(bar){bar.style.background='#fff4df';const b=bar.querySelector('[data-save-order]');if(b)b.textContent='💾 حفظ الترتيب'}}
 function move(c,card,delta){const cards=[...c.children],i=cards.indexOf(card),j=i+delta;if(j<0||j>=cards.length)return;if(delta<0)c.insertBefore(card,cards[j]);else c.insertBefore(card,cards[j].nextSibling);renumber(c);dirty()}
 async function enable(token){if(token!==runToken)return false;cleanup();let data;try{data=await request({action:'get_project',slug:currentSlug})}catch(e){return false}if(token!==runToken)return false;const pages=data.pages||[];if(!pages.length)return false;const c=findContainer(pages.length);if(!c)return false;
 [...c.children].forEach((card,i)=>{card.dataset.pageId=pages[i].id;card.style.position='relative';card.style.userSelect='none';card.style.paddingInlineStart='88px';card.draggable=true;const controls=document.createElement('div');controls.className='page-order-controls';controls.style.cssText='position:absolute;inset-inline-start:10px;top:50%;transform:translateY(-50%);display:flex;gap:5px;z-index:50';const up=document.createElement('button'),down=document.createElement('button');up.type=down.type='button';up.textContent='↑';down.textContent='↓';[up,down].forEach(b=>b.style.cssText='width:34px;height:38px;border:0;border-radius:9px;background:#6d4aff;color:#fff;font-size:21px;font-weight:900;padding:0;cursor:pointer');up.onclick=e=>{e.preventDefault();e.stopPropagation();move(c,card,-1)};down.onclick=e=>{e.preventDefault();e.stopPropagation();move(c,card,1)};controls.append(up,down);card.append(controls);const handle=document.createElement('span');handle.className='page-drag-handle';handle.textContent='↕';handle.style.cssText='position:absolute;inset-inline-end:12px;top:10px;font-size:24px;font-weight:900;color:#6d4aff;cursor:grab;z-index:40';card.append(handle);card.addEventListener('dragstart',e=>{card.classList.add('dragging-page');card.style.opacity='.45';e.dataTransfer.setData('text/plain',card.dataset.pageId)});card.addEventListener('dragend',()=>{card.style.opacity='1';card.classList.remove('dragging-page')});card.addEventListener('dragover',e=>{e.preventDefault();const drag=c.querySelector('.dragging-page');if(!drag||drag===card)return;const r=card.getBoundingClientRect();c.insertBefore(drag,e.clientY<r.top+r.height/2?card:card.nextSibling);renumber(c);dirty()})});
 cleanupBarOnly();const bar=document.createElement('div');bar.id='pageOrderBar';bar.className='page-order-bar';bar.style.cssText='display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap;background:#f4f1ff;padding:12px 14px;border-radius:12px;margin:12px 0;color:#4933a8;font-weight:700';bar.innerHTML='<span>ترتيب الصفحات: ↑ ↓ على الهاتف، والسحب ↕ على اللابتوب.</span>';const save=document.createElement('button');save.type='button';save.dataset.saveOrder='1';save.textContent='💾 حفظ الترتيب';save.style.cssText='background:#6d4aff;color:#fff;border:0;border-radius:9px;padding:10px 15px;font-weight:800;cursor:pointer';save.onclick=async()=>{const ids=[...c.children].map(x=>x.dataset.pageId);try{save.disabled=true;save.textContent='⏳ جاري الحفظ...';await request({action:'reorder_pages',slug:currentSlug,page_ids:ids});save.textContent='✓ تم الحفظ';bar.style.background='#eefbf1'}catch(e){alert(e.message);save.textContent='💾 حفظ الترتيب'}finally{save.disabled=false}};bar.append(save);c.parentElement.insertBefore(bar,c);return true}
 function cleanupBarOnly(){document.querySelectorAll('#pageOrderBar,.page-order-bar').forEach(x=>x.remove())}
 function arm(){const token=++runToken;let n=0;const t=setInterval(async()=>{n++;if(token!==runToken||await enable(token)||n>35)clearInterval(t)},150)}
 function wait(){if(typeof window.openEditor!=='function')return setTimeout(wait,50);const base=window.openEditor;window.openEditor=async function(slug){currentSlug=slug;runToken++;cleanup();const r=await base(slug);setTimeout(arm,120);return r}}
 wait();
})();