/* Drag/drop page ordering with permanent Supabase persistence. Page IDs stay unchanged. */
(function(){
 let currentSlug='';
 const ENDPOINT='https://jzswtwicvgppisasrkqe.supabase.co/functions/v1/creator-projects';
 function password(){let p=sessionStorage.getItem('creatorPassword');if(!p){p=prompt('أدخلي كلمة مرور لوحة غادة')||'';if(p)sessionStorage.setItem('creatorPassword',p)}return p}
 async function saveOrder(pageIds){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reorder_pages',slug:currentSlug,page_ids:pageIds,password:password()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر حفظ ترتيب الصفحات');return d}
 const wait=()=>{if(typeof window.openEditor!=='function')return setTimeout(wait,60);const base=window.openEditor;window.openEditor=async function(slug){currentSlug=slug;const r=await base(slug);setTimeout(enable,140);return r};};
 function enable(){const panel=document.querySelector('.panel');if(!panel)return;const pageContainer=[...panel.querySelectorAll('div')].find(d=>{const kids=[...d.children];return kids.length>0&&kids.every(x=>x.tagName==='DIV'&&x.style.cursor==='pointer')});if(!pageContainer||pageContainer.dataset.reorderReady)return;pageContainer.dataset.reorderReady='1';
  const cards=[...pageContainer.children];cards.forEach((card,i)=>{card.draggable=true;card.dataset.pageId=card.__pageId||'';card.dataset.originalIndex=i;card.style.position='relative';card.style.paddingRight='54px';const handle=document.createElement('span');handle.textContent='☰';handle.title='اسحبي لترتيب الصفحة';handle.style.cssText='position:absolute;right:16px;top:50%;transform:translateY(-50%);font-size:25px;cursor:grab;user-select:none;color:#6d4aff';card.append(handle);card.addEventListener('dragstart',e=>{card.classList.add('dragging-page');card.style.opacity='.45';e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>{card.style.opacity='1';card.classList.remove('dragging-page')});card.addEventListener('dragover',e=>{e.preventDefault();const dragging=pageContainer.querySelector('.dragging-page');if(!dragging||dragging===card)return;const r=card.getBoundingClientRect();if(e.clientY<r.top+r.height/2)pageContainer.insertBefore(dragging,card);else pageContainer.insertBefore(dragging,card.nextSibling);renumber(pageContainer);showDirty()})});
  /* Recover stable page IDs from each card's click closure by matching displayed page title to current server order. */
  fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'get_project',slug:currentSlug,password:password()})}).then(r=>r.json()).then(d=>{const serverPages=d.pages||[];[...pageContainer.children].forEach((c,i)=>{if(serverPages[i])c.dataset.pageId=serverPages[i].id})}).catch(()=>{});
  const bar=document.createElement('div');bar.id='pageOrderBar';bar.style.cssText='display:flex;gap:8px;align-items:center;flex-wrap:wrap;background:#f4f1ff;padding:10px 12px;border-radius:10px;margin:10px 0;color:#4933a8;font-weight:700';const text=document.createElement('span');text.textContent='☰ اسحبي الصفحات ثم اضغطي حفظ الترتيب.';const save=document.createElement('button');save.textContent='💾 حفظ الترتيب';save.style.cssText='background:#6d4aff;color:#fff;border:0;border-radius:9px;padding:9px 14px;font-weight:800;cursor:pointer';save.onclick=async()=>{const ids=[...pageContainer.children].map(c=>c.dataset.pageId).filter(Boolean);if(ids.length!==pageContainer.children.length)return alert('انتظري ثانية حتى تجهز الصفحات ثم جربي الحفظ.');try{save.disabled=true;save.textContent='⏳ جاري الحفظ...';await saveOrder(ids);save.textContent='✓ تم حفظ الترتيب';bar.style.background='#eefbf1';setTimeout(()=>{save.textContent='💾 حفظ الترتيب'},1800)}catch(e){alert(e.message);save.textContent='💾 حفظ الترتيب'}finally{save.disabled=false}};bar.append(text,save);pageContainer.parentElement.insertBefore(bar,pageContainer)
 }
 function renumber(container){[...container.children].forEach((c,i)=>{const strong=c.querySelector('strong');if(strong)strong.textContent=strong.textContent.replace(/^\d+\./,(i+1)+'.')})}
 function showDirty(){const b=document.querySelector('#pageOrderBar button');if(b){b.textContent='💾 حفظ الترتيب';b.parentElement.style.background='#fff4df'}}
 wait();
})();