/* Interactive preview: image pages + full video pages + hotspots */
(function(){
const playEndpoint='https://jzswtwicvgppisasrkqe.supabase.co/functions/v1/creator-video-plays',projectEndpoint='https://jzswtwicvgppisasrkqe.supabase.co/functions/v1/creator-projects';
function actionName(a){return({next:'▶ التالي',prev:'◀ السابق',page:'🔢 123 صفحة',url:'🔗 رابط',whatsapp:'💬 واتساب',video:'🎬 فيديو',audio:'🔊 صوت',map:'📍 خريطة',home:'🏠 الرئيسية'})[a]||'زر'}function sessionId(){let id=sessionStorage.getItem('ghadaVideoSession');if(!id){id=crypto.randomUUID();sessionStorage.setItem('ghadaVideoSession',id)}return id}function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||''}}catch{}return''}async function track(page,id,type){try{await fetch(playEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_id:page.id,hotspot_id:id||'page-video',source_type:type,session_id:sessionId()})})}catch{}}
window.interactivePreview=function(d,startPage,startVariant){let current=startPage,variant=startVariant||'portrait',showHotspots=true;const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:100000;background:#171717;overflow:hidden';const toolbar=document.createElement('div');toolbar.style.cssText='position:absolute;top:10px;left:10px;right:10px;z-index:999;display:flex;gap:8px;justify-content:center;flex-wrap:wrap';const stage=document.createElement('div');stage.style.cssText='position:absolute;inset:0;background:#111;display:flex;align-items:center;justify-content:center';function tb(t){const b=document.createElement('button');b.textContent=t;b.style.cssText='padding:10px 14px;border:0;border-radius:10px;background:rgba(0,0,0,.78);color:#fff;font-weight:700';return b}const portrait=tb('📱 طولية'),landscape=tb('💻 عرضية'),eye=tb('👁 الأزرار ظاهرة'),close=tb('✕ خروج');toolbar.append(portrait,landscape,eye,close);overlay.append(stage,toolbar);document.body.appendChild(overlay);function updateEye(){eye.textContent=showHotspots?'👁 الأزرار ظاهرة':'🙈 الأزرار مخفية'}portrait.onclick=()=>{variant='portrait';render()};landscape.onclick=()=>{variant='landscape';render()};eye.onclick=()=>{showHotspots=!showHotspots;updateEye();render()};close.onclick=()=>overlay.remove();async function refreshVideoPage(p){if(p?.page_type!=='video')return p;try{const password=sessionStorage.getItem('creatorPassword')||'',slug=d.project?.slug;if(!password||!slug)return p;const r=await fetch(projectEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,action:'get_project',slug})}),fresh=await r.json();if(!r.ok)return p;const fp=(fresh.pages||[]).find(x=>x.id===p.id);if(fp){Object.assign(p,fp);const local=d.pages.find(x=>x.id===p.id);if(local&&local!==p)Object.assign(local,fp)}return p}catch{return p}}async function go(p){if(!p)return alert('الصفحة المطلوبة غير موجودة');current=p;if(p.page_type==='video'){stage.innerHTML='<div style="color:white;font:20px system-ui">⏳ جاري تحميل الفيديو...</div>';await refreshVideoPage(p)}render()}
function modalBase(){const m=document.createElement('div');m.style.cssText='position:absolute;inset:0;z-index:2000;background:rgba(0,0,0,.96);display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box';const x=document.createElement('button');x.textContent='✕ إغلاق الفيديو';x.style.cssText='position:absolute;top:18px;right:18px;z-index:5;padding:11px 15px;border:0;border-radius:12px;background:rgba(0,0,0,.75);color:#fff;font-weight:800';x.onclick=()=>m.remove();m.appendChild(x);stage.appendChild(m);return m}function openVideo(h){if(!h.target)return;const yid=youtubeId(h.target);if(yid){const m=modalBase(),f=document.createElement('iframe');f.src='https://www.youtube.com/embed/'+encodeURIComponent(yid)+'?autoplay=1&playsinline=1';f.allow='autoplay; encrypted-media; picture-in-picture';f.allowFullscreen=true;f.style.cssText='width:min(100%,1000px);height:min(80vh,562px);border:0;background:#000';m.appendChild(f);track(current,h.id||h.groupId,'youtube');return}const m=modalBase(),v=document.createElement('video');v.src=h.target;v.controls=true;v.autoplay=true;v.playsInline=true;v.preload='metadata';v.style.cssText='max-width:100%;max-height:100%;background:#000;object-fit:contain';let counted=false;v.onplaying=()=>{if(!counted){counted=true;track(current,h.id||h.groupId,h.videoSourceType==='upload'?'upload':'direct')}};m.appendChild(v);v.play().catch(()=>{})}function act(h){const idx=d.pages.findIndex(p=>p.id===current.id);if(h.action==='next')return go(d.pages[idx+1]);if(h.action==='prev')return go(d.pages[idx-1]);if(h.action==='home')return go(d.pages[0]);if(h.action==='page')return go(d.pages.find(p=>p.id===h.target));if(h.action==='whatsapp'){const phone=(h.target||'').replace(/[^0-9]/g,'');return window.open('https://wa.me/'+phone+(h.message?'?text='+encodeURIComponent(h.message):''),'_blank')};if((h.action==='url'||h.action==='map')&&h.target)return window.open(h.target,'_blank');if(h.action==='video')return openVideo(h)}
function renderVideoPage(){eye.style.display='none';const s=current.video_settings||{};let src=s[variant]||s[variant==='portrait'?'landscape':'portrait'];if(typeof src==='string')src={url:src,source:'direct'};if(!src?.url){stage.innerHTML='<div style="color:white;font:20px system-ui;text-align:center">لا يوجد فيديو محفوظ لهذه الصفحة. افتحي تحرير صفحة الفيديو واحفظي الفيديو مرة أخرى.</div>';return}const frame=document.createElement('div');frame.style.cssText=variant==='portrait'?'position:relative;height:100%;max-height:100vh;aspect-ratio:9/16;background:#000;overflow:hidden':'position:relative;width:100%;height:100%;background:#000;overflow:hidden';const yid=youtubeId(src.url),idx=d.pages.findIndex(p=>p.id===current.id);if(yid){const f=document.createElement('iframe');f.src='https://www.youtube.com/embed/'+encodeURIComponent(yid)+'?autoplay='+(s.autoplay===false?'0':'1')+'&playsinline=1&rel=0';f.allow='autoplay; encrypted-media; picture-in-picture';f.allowFullscreen=true;f.style.cssText='position:absolute;inset:0;width:100%;height:100%;border:0;background:#000';frame.appendChild(f);track(current,'page-'+variant,'youtube')}else{const v=document.createElement('video');v.src=src.url;v.controls=true;v.playsInline=true;v.preload='auto';v.autoplay=s.autoplay!==false;v.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#000';let counted=false;v.onplaying=()=>{if(!counted){counted=true;track(current,'page-'+variant,src.source==='upload'?'upload':'direct')}};if(s.advanceOnEnd)v.onended=()=>{if(d.pages[idx+1])go(d.pages[idx+1])};frame.appendChild(v);if(s.autoplay!==false)v.play().catch(()=>{})}
// Video-page interactive buttons
function renderVideoButtons(frame){
 const buttons=Array.isArray(current.video_settings?.buttons)?current.video_settings.buttons:[];
 buttons.filter(b=>b.variant===variant).forEach((h,i)=>{
  const b=document.createElement('button'); b.type='button';
  const rad=h.shape==='circle'||h.shape==='oval'?'50%':h.shape==='pill'?'999px':h.shape==='square'?'4px':'12px';
  b.textContent=h.label||actionName(h.action);
  b.style.cssText='position:absolute;left:'+Number(h.x||0)+'%;top:'+Number(h.y||0)+'%;width:'+Number(h.w||20)+'%;height:'+Number(h.h||10)+'%;z-index:'+(500+i)+';cursor:pointer;background:'+(h.background||'#6d4aff')+';color:'+(h.textColor||'#fff')+';border:2px solid rgba(255,255,255,.9);border-radius:'+rad+';font-weight:800;font-size:clamp(12px,2vw,18px);box-shadow:0 4px 14px rgba(0,0,0,.35)';if(h.animation==='pulse')b.animate([{transform:'scale(1)'},{transform:'scale(1.06)'},{transform:'scale(1)'}],{duration:1600,iterations:Infinity,easing:'ease-in-out'});else if(h.animation==='float')b.animate([{transform:'translateY(0)'},{transform:'translateY(-5px)'},{transform:'translateY(0)'}],{duration:2200,iterations:Infinity,easing:'ease-in-out'});else if(h.animation==='glow')b.animate([{boxShadow:'0 4px 14px rgba(0,0,0,.35)'},{boxShadow:'0 4px 24px rgba(109,74,255,.8)'},{boxShadow:'0 4px 14px rgba(0,0,0,.35)'}],{duration:1800,iterations:Infinity,easing:'ease-in-out'});
  b.onclick=e=>{e.preventDefault();e.stopPropagation();act(h)};
  frame.appendChild(b);
 });
}
stage.appendChild(frame); renderVideoButtons(frame)}
function render(){stage.innerHTML='';updateEye();portrait.style.background=variant==='portrait'?'#6d4aff':'rgba(0,0,0,.78)';landscape.style.background=variant==='landscape'?'#6d4aff':'rgba(0,0,0,.78)';if(current.page_type==='video'){renderVideoPage();return}eye.style.display='';const media=variant==='portrait'?current.settings?.image_portrait:current.settings?.image_landscape;if(!media){stage.innerHTML='<div style="color:white;font:20px system-ui">لا توجد صورة لهذه النسخة</div>';return}const frame=document.createElement('div');frame.style.cssText=variant==='portrait'?'position:relative;height:100%;max-height:100vh;aspect-ratio:9/16;background:#000;overflow:hidden':'position:relative;width:100%;max-width:100vw;aspect-ratio:16/9;background:#000;overflow:hidden';const img=document.createElement('img');img.src=media.url;img.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:fill';frame.appendChild(img);(current.hotspots||[]).filter(h=>h.variant===variant).forEach((h,i)=>{const b=document.createElement('button');b.type='button';const rad=h.shape==='circle'||h.shape==='oval'?'50%':h.shape==='pill'?'999px':h.shape==='round'?'18px':'0';let visual='background:transparent;border:0;';if(showHotspots)visual=`background:rgba(109,74,255,.18);border:3px dashed #6d4aff;color:#fff;border-radius:${rad};`;else if(h.kind==='styled')visual=`background:${h.background||'#22c55e'};color:${h.textColor||'#fff'};border:0;border-radius:${rad};font-weight:bold;`;b.style.cssText=`position:absolute;left:${h.x}%;top:${h.y}%;width:${h.w}%;height:${h.h}%;z-index:${100+i};cursor:pointer;${visual}`;if(showHotspots)b.textContent='#'+(i+1)+' '+actionName(h.action);else if(h.kind==='styled')b.textContent=h.label||'';b.onclick=e=>{e.preventDefault();e.stopPropagation();act(h)};frame.appendChild(b)});stage.appendChild(frame)}render()};
})();